// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Room struct {
	ID        int64     `json:"id"`
	Roomname  string    `json:"roomname"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Userroom struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}
